apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: restaurant
spec:
  type: NodePort
  selector:
    app: restaurant-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
